### ISSUE TITLE
Failed to installation of Rtools version 40

### ISSUE THREAD

**Issue by zeweimiao** [r-windows/rtools-installer#5]
![Image 1](https://user-images.githubusercontent.com/25963336/55972034-4c5bdc00-5c48-11e9-9819-180861c3352d.png)

**Comment by jeroen** [comment]
Thank you! The problem is fixed and new installers are available at: http://dl.bintray.com/rtools/installer/

Can you test if this works now for you?

**Comment by jeroen** [comment]
Thank you! The problem is fixed and new installers are available at: http://dl.bintray.com/rtools/installer/

Can you test if this works now for you?

**Comment by zeweimiao** [comment]
Jeroen:

Thanks very much for your reply. I’ve tried the new link (rtools40-x86_64.exe<http://dl.bintray.com/rtools/installer/:rtools40-x86_64.exe>) you just shared a few minutes ago.  Unfortunately,<http://dl.bintray.com/rtools/installer/:rtools40-x86_64.exe> the same error still comes up. Thanks very much.

[cid:image001.png@01D4F05E.840CF220]

Sincerely,

Zewei

**Comment by jeroen** [comment]
That is very odd. Is it exactly the same error message with `HKEY_LOCAL_MACHINE`? Because that should no longer be used in the new installer.

**Comment by zeweimiao** [comment]
Yes. I just use the same machine and close R and Rstudio and double click your link. We get the same error. Thanks.

**Comment by jeroen** [comment]
Forgot to fix it in the 64 bit installer 🤦‍♂

**Comment by jeroen** [comment]
This is now fixed for real.
